apiVersion: v1
kind: ServiceAccount
metadata:
  name: containerssh-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerssh-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: containerssh-role-binding
subjects:
- kind: ServiceAccount
  name: containerssh-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: containerssh-role
  apiGroup: rbac.authorization.k8s.io
